name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "liuji.site"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker-io.liuji.site", custom_domain = true },
#   { pattern = "gcr-io.liuji.site", custom_domain = true },
#   { pattern = "ghcr-io.liuji.site", custom_domain = true },
#   { pattern = "quay-io.liuji.site", custom_domain = true },
#   { pattern = "registry-k8s-io.liuji.site", custom_domain = true },
#   { pattern = "docker.liuji.site", custom_domain = true },
#   { pattern = "github.liuji.site", custom_domain = true },
#   { pattern = "raw-githubusercontent-com.liuji.site", custom_domain = true },
#   { pattern = "github-io.liuji.site", custom_domain = true },
#   { pattern = "grafana-github-io.liuji.site", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "liuji.site"
